### ISSUE TITLE
Can super-save save silently?

### ISSUE THREAD

**Issue by alienbogart** [bbatsov/super-save#22]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
of 2018-11-28
- Evil version 1.2.13
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- super-save-20180929.727/

Since I already have a modification indicator in the modeline, I'd like to hide the saving messages in the echo area.

**Comment by alphapapa** [comment]
Nothing in `super-save` prints a message.  You could override the `message` function yourself in advice to e.g. `super-save-command`.

**Comment by cireu** [comment]
When you saving a buffer, Emacs will call `write-region` function to write your changes to disks. However, this function will force refresh your minibuffer, what `(setq save-silently t)` done just using a temp empty message to override your minibuffer. It can't be fixed by using elisp.

I've tried what @alphapapa have said, advice`message` or even `files--message` or make them flet-bound to nil. But all this messures doesn't works.

**Comment by alienbogart** [comment]
My issue was the pollution in the echo area, and `(setq save-silently t)` seems to have solved it. I'll close the issue for now.
